### ISSUE TITLE
How to raise slippage

### ISSUE THREAD

**Issue by thanglv1302** [religion-counter/onlyone#6]
![image](https://user-images.githubusercontent.com/38907843/128040726-75293cf3-288f-4743-bf5f-fd10eaa48a71.png)
Hi @religion-counter , I have built and buy the success token following:
https://github.com/religion-counter/onlyone/blob/main/helper-scripts/buy-onlyone-pancakeswap.js
But, I wanna raise slippage. You know, many tokens have slippage very high. Please give me your opinion. Thanks.

**Comment by religion-counter** [comment]
The slippage is something the pancakeswap interface offers for setting the minAmountOut parameter. When you set this to 1 you always buy on the market price. If you want to precisely calculate the slippage you will need another library from https://github.com/pancakeswap/pancake-swap-sdk or have some other way to calculate the current market price and calculate the minAmount your way. The easiest way is to set minAmountOut as 1 or 0 and you will always buy on the market price.

**Comment by thanglv1302** [comment]
Thank @religion-counter, I see variable minAmountOut have value > 100. Did I miss understand? (The easiest way is to set minAmountOut as 1 or 0 and you will always buy on the market price.)
https://github.com/religion-counter/onlyone/blob/main/helper-scripts/buy-onlyone-pancakeswap.js#L49

**Comment by religion-counter** [comment]
@thanglv1302 Yes, this is just an example. If you read the docs https://docs.uniswap.org/protocol/V2/reference/smart-contracts/router-02#swapexactethfortokens 

amountOutMin | uint | The minimum amount of output tokens that must be received for the transaction not to revert.

So if you want your transaction not to revert you need to set this to the minimum value.

**Comment by thanglv1302** [comment]
@religion-counter, thank you for sharing.
