### ISSUE TITLE
Approve the transaction when sell token

### ISSUE THREAD

**Issue by thanglv1302** [religion-counter/onlyone#7]
Hi @religion-counter, I have a question about the source code in "sell-onlyone-pancakeswap.js" file:

What approves the transaction when sell the token? Is it necessary or not?
I have commented code about Approve ONLYONE spend from line 50 - 67. I have still sell the token. Can you explain it , please?
https://github.com/religion-counter/onlyone/blob/c402ad334bdcc38827f42a5de707e0dea7bd8bd7/helper-scripts/sell-onlyone-pancakeswap.js#L50

**Comment by religion-counter** [comment]
Hi @thanglv1302 ,
The following code approves the sell. It is needed only for the first sell transaction of a particular token if you haven't approved it already. If the token is approved for selling for the pancake swap router address you don't need it.
```
    // Approve ONLYONE spend
    var onlyoneContract = new web3.eth.Contract(abiArray, tokenAddress, {from: targetAccount.address});
    var approveOnlyoneSpendData = onlyoneContract.methods.approve(pancakeSwapRouterAddress, web3.utils.toWei('1', 'ether'));
    var count = await web3.eth.getTransactionCount(targetAccount.address);
    var rawTransactionApprove = {
        "from":targetAccount.address,
        "gasPrice":web3.utils.toHex(5000000000),
        "gasLimit":web3.utils.toHex(210000),
        "to":tokenAddress,
        "value":"0x0",
        "data":approveOnlyoneSpendData.encodeABI(),
        "nonce":web3.utils.toHex(count)
    };
    var transactionApprove = new Tx(rawTransactionApprove, {'common':BSC_FORK});
    transactionApprove.sign(privateKey)

    var resultApprove = await web3.eth.sendSignedTransaction('0x' + transactionApprove.serialize().toString('hex'));
    console.log("Approved" + resultApprove);
```
Regards

**Comment by thanglv1302** [comment]
@religion-counter thank you for sharing, I got it. I see you that very good about crypto. Could you sharing the document about API web3? Example: Why do you know the first sell need implement approve transaction?
Thanks!

**Comment by thanglv1302** [comment]
Thanks @religion-counter, you truly humble. Thanks to your sharing, I have coding finish the bot. 
Thank mate very much!
Hope you had a good weekend :)
