### ISSUE TITLE
How to get Amount a token in my wallet metamask (BSC)

### ISSUE THREAD

**Issue by thanglv-1330** [religion-counter/onlyone#8]
Hi @religion-counter, I have an issue that needs suggestions from you:
`How to get Amount a token in my wallet metamask (BSC)?`
Please give me your opinion.
Thanks

**Comment by religion-counter** [comment]
You need to use the ```balanceOf(address)``` method of the token contract ABI.
You can check https://piyopiyo.medium.com/how-to-get-erc20-token-balance-with-web3-js-206df52f2561 and comment whether it works for your token.

**Comment by thanglv-1330** [comment]
Hi @religion-counter, thank you very much, great teacher!

**Comment by thanglv-1330** [comment]
Hi @religion-counter, thank you very much, great teacher!
