### ISSUE TITLE
[SELL_TOKEN] Should using swapExactTokensForETH to sell token?

### ISSUE THREAD

**Issue by thanglv-1330** [religion-counter/onlyone#9]
Hi @religion-counter, I am using function "swapExactTokensForETHSupportingFeeOnTransferTokens" to sell token following your example: https://github.com/religion-counter/onlyone/blob/main/helper-scripts/sell-onlyone-pancakeswap.js#L76.
--> I found out 2 issues:
1. Some token can't swap: 
example: 0x3e900195b93423b8e7bddd63d1d51c02fd18ccdf. I have changed using swapExactTokensForETH replace swapExactTokensForETHSupportingFeeOnTransferTokens, sell success.
2. I have read the document and found out that: using swapExactTokensForETH better
"Identical to swapExactTokensForETH, but succeeds for tokens that take a fee on transfer."
![image](https://user-images.githubusercontent.com/49554519/128659857-bf125d52-ab1f-40f9-9f2f-17660c29ad20.png)
--> Please give me your opinion about the pros and cons of functions:
- swapExactTokensForETHSupportingFeeOnTransferTokens
- swapExactTokensForETH

**Comment by religion-counter** [comment]
Hi @thanglv-1330 ,
There are some tokens that take fee - percentage of each transfer is automatically taken like the ONLYONE token in the example.
For tokens that doesn't take fees you should better use swapExactTokensForETH method.
Fee is used for example for marketing, reflection and others. ONLYONE token takes fees to add to the liquidity pool to create a steadily increasing price for the token.

**Comment by thanglv-1330** [comment]
Hi @religion-counter, thank you for sharing. So, what any way to check tokens take fees? tokens don't take fees?
Thanks!

**Comment by religion-counter** [comment]
Hi @thanglv-1330,
You can check the token fees in the token contract code. For example for the ONLYONE token the fees are in https://bscscan.com/address/0xb899dB682e6D6164D885ff67C1e676141deaaA40#code in line # 717

**Comment by religion-counter** [comment]
These are the initial fees. The current fees can be read in https://bscscan.com/address/0xb899dB682e6D6164D885ff67C1e676141deaaA40#readContract

**Comment by thanglv-1330** [comment]
@religion-counter, thank you very much.
